### PR TITLE
PRO-1642 Updates demo for A3 stable

### PR DESCRIPTION
**Pull request by abea**
This is the demo site we used for the [gatsby plugin demo](https://apostrophecms.com/blog/building-a-gatsby-site-with-apostrophecms-data-part-2). This PR updates it to use A3 stable, getting rid of the project-level webpack.

### CODE REVIEW

**Review by gregvanbrug — CHANGES_REQUESTED** [review]
Everything here looks fine but I'm getting a `404` on `main.css` when running the app. It also looks like the generated `site.css` file is not ignored by git.

**Comment by abea** [comment]
good catch. old file.

**Review by gregvanbrug — APPROVED** [review]
🤦 Sorry @abea I thought I had approved this days ago....

**Comment by abea** [comment]
gracias

**Pull request merged**
